logging:
  config: classpath:log4j2.xml
  level:
    root: info

server:
  port: 8021
#  servlet:
#    context-path: /api

spring:
  webflux:
    base-path: /api
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/MECM
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: mecmapp
      password: MECMAPP#682c11386f13420ca9bdf376fb01b1c2
      idle-timeout: 300000
      connection-timeout: 20000
      maximum-pool-size: 20
      auto-commit: true

# noinspection undefined
mecm:
  auth:
    token:
      entitlement: |
        {"authType":"SEA","source":"user-service","sessionToken":""}
  user:
    base-path: /user